---
name: model_architecture_config
date: 2019-03-03
paper: https://arxiv.org/pdf/1408.5882.pdf

arch:
  cnn:
    units:         100         # Number of convNets in each layers
    min_filter:    3           # Minimum size of the filter
    max_filter:    5           # Maximum size of the filter
    kernel_l2_reg: 1           # L2 regularisation for each kernel in conv layer
  
  layers:
    dropout:       0.5         # Dropout rate in the layer
  
  fit:
    device:        CPU         # Device to build the model
    epochs:        6           # Number of epochs
    batch_size:    50          # Number of datapoint in the batch
    optimizer:     adagrad     # Optimizer to use
    backend:       tensorflow  # Neural Network Framework used
    learning_rate: 0.01        # The initial learning rate
  
  data:
    root_path:     ./data/     # Root data path 
    vocab_size:    15000       # Vocabulary size
    embedding:     300         # Size of the embedding output
  
  initialisation:
    embedding:     False        # Use pretrained embedding for initialisation
    bin_path:      ../GoogleNews-vectors-negative300.bin
    
#   logging:
#     tensorboard:
#       dir:
#       port:
  
  